### ISSUE TITLE
Decouple `SimulatorEventLoop` from concatenation of trajectories

### ISSUE THREAD

**Issue by SamWitty** [BasisResearch/chirho#289] opened 2023-09-22 20:15 UTC
Currently, in the `staging-dynamics` branch the `SimulatorEventLoop` is responsible for tracking and executing interruptions, simulating the dynamical system between interruption events, and concatenating the results into a single trajectory. However, the concatenation of trajectories can/should be decoupled from managing interruptions.

To address this `simulate` should by default only return the final state of the trajectory, and thus the `SimulatorEventLoop` is by-default only responsible for producing the final state of the final simulation after all interruptions have been introduced.

We can/should then introduce a separate `Logging` effect handler for returning trajectories rather than the default behavior of returning the final state. `Logging` and `SimulatorEventLoop` should be modular and freely compose.

**Comment by eb8680** [comment] 2023-09-24 03:01
Dupe of #159?

**Comment by SamWitty** [comment] 2023-09-24 03:59
Yes, will close #159 in favor of this more descriptive issue.

**Comment by SamWitty** [comment] 2023-09-24 04:41
Blocked by #290

**Closed** 2023-10-03 19:27 UTC
Labels: refactor, feature:dynamics
